/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Base64, Base64Interface } from "../Base64";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x86bd94fb",
        type: "bytes32",
      },
    ],
    name: "c_0x86bd94fb",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063f821457d146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220cb25b0dad7b59b2aa8715a46a90c9252fd3f00f2974d40cabcfbcf7ed972d3d864736f6c63430008040033";

export class Base64__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Base64> {
    return super.deploy(overrides || {}) as Promise<Base64>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Base64 {
    return super.attach(address) as Base64;
  }
  connect(signer: Signer): Base64__factory {
    return super.connect(signer) as Base64__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Base64Interface {
    return new utils.Interface(_abi) as Base64Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Base64 {
    return new Contract(address, _abi, signerOrProvider) as Base64;
  }
}
